import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class AplikasiKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhu
     */
    public AplikasiKonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        JOptionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputTextField = new javax.swing.JTextField();
        comboBoxSkala = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        hasilLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Konversi Suhu");

        jLabel2.setText("Masukkan Suhu : ");

        inputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTextFieldKeyTyped(evt);
            }
        });

        comboBoxSkala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        comboBoxSkala.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxSkalaItemStateChanged(evt);
            }
        });
        comboBoxSkala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSkalaActionPerformed(evt);
            }
        });

        jButton1.setText("Konversi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Celcius");
        jRadioButton1.setName(""); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Fahrenheit");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Reamur");
        jRadioButton3.setBorderPainted(true);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Kelvin");

        javax.swing.GroupLayout JOptionPanelLayout = new javax.swing.GroupLayout(JOptionPanel);
        JOptionPanel.setLayout(JOptionPanelLayout);
        JOptionPanelLayout.setHorizontalGroup(
            JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JOptionPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JOptionPanelLayout.createSequentialGroup()
                        .addGroup(JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JOptionPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboBoxSkala, javax.swing.GroupLayout.Alignment.LEADING, 0, 151, Short.MAX_VALUE)
                                    .addComponent(inputTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JOptionPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(hasilLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JOptionPanelLayout.setVerticalGroup(
            JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JOptionPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(comboBoxSkala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1))
                .addGap(31, 31, 31)
                .addGroup(JOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSkalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSkalaActionPerformed
                                              

    }//GEN-LAST:event_comboBoxSkalaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                        
    try {
    double suhuInput = Double.parseDouble(inputTextField.getText());
    String skalaInput = (String) comboBoxSkala.getSelectedItem();
    double hasilKonversi = 0;
    String skalaTujuan = "";

    // Pilih konversi berdasarkan skala input yang dipilih
    if (skalaInput.equals("Celcius")) {
        if (jRadioButton3.isSelected()) {
            hasilKonversi = suhuInput * 4 / 5; // Celcius ke Reamur
            skalaTujuan = "Reamur";
        } else if (jRadioButton2.isSelected()) {
            hasilKonversi = (suhuInput * 9 / 5) + 32; // Celcius ke Fahrenheit
            skalaTujuan = "Fahrenheit";
        } else if (jRadioButton4.isSelected()) {
            hasilKonversi = suhuInput + 273.15; // Celcius ke Kelvin
            skalaTujuan = "Kelvin";
        }
    } else if (skalaInput.equals("Fahrenheit")) {
        if (jRadioButton1.isSelected()) {
            hasilKonversi = (suhuInput - 32) * 5 / 9; // Fahrenheit ke Celcius
            skalaTujuan = "Celcius";
        } else if (jRadioButton3.isSelected()) {
            hasilKonversi = (suhuInput - 32) * 4 / 9; // Fahrenheit ke Reamur
            skalaTujuan = "Reamur";
        } else if (jRadioButton4.isSelected()) {
            hasilKonversi = (suhuInput - 32) * 5 / 9 + 273.15; // Fahrenheit ke Kelvin
            skalaTujuan = "Kelvin";
        }
    } else if (skalaInput.equals("Reamur")) {
        if (jRadioButton1.isSelected()) {
            hasilKonversi = suhuInput * 5 / 4; // Reamur ke Celcius
            skalaTujuan = "Celcius";
        } else if (jRadioButton2.isSelected()) {
            hasilKonversi = (suhuInput * 9 / 4) + 32; // Reamur ke Fahrenheit
            skalaTujuan = "Fahrenheit";
        } else if (jRadioButton4.isSelected()) {
            hasilKonversi = (suhuInput * 5 / 4) + 273.15; // Reamur ke Kelvin
            skalaTujuan = "Kelvin";
        }
    } else if (skalaInput.equals("Kelvin")) {
        if (jRadioButton1.isSelected()) {
            hasilKonversi = suhuInput - 273.15; // Kelvin ke Celcius
            skalaTujuan = "Celcius";
        } else if (jRadioButton2.isSelected()) {
            hasilKonversi = (suhuInput - 273.15) * 9 / 5 + 32; // Kelvin ke Fahrenheit
            skalaTujuan = "Fahrenheit";
        } else if (jRadioButton3.isSelected()) {
            hasilKonversi = (suhuInput - 273.15) * 4 / 5; // Kelvin ke Reamur
            skalaTujuan = "Reamur";
        }
    }

    // Tampilkan hasil konversi
    hasilLabel.setText("Hasil Konversi: " + hasilKonversi + " " + skalaTujuan);
} catch (NumberFormatException e) {
    // Menampilkan pesan error jika input bukan angka
    JOptionPane.showMessageDialog(this, "Masukkan angka terlebih dahulu!", "Input Error", JOptionPane.ERROR_MESSAGE);
    inputTextField.setText("");
}



    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextFieldKeyTyped
                                      
    char karakter = evt.getKeyChar();
    
    // Memeriksa apakah karakter bukan angka atau titik desimal
    if (!Character.isDigit(karakter) && karakter != '.') {
        evt.consume(); // Mengabaikan karakter yang tidak valid
    }

    }//GEN-LAST:event_inputTextFieldKeyTyped

    private void comboBoxSkalaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxSkalaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSkalaItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JOptionPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> comboBoxSkala;
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
